### ISSUE TITLE
 Cannot access 'execa' before initialization at getFFprobeWrappedExecution

### ISSUE THREAD

**Issue by BabuBahir** [caffco/get-video-duration#21]
I am unable to use this npm package in my angular component .

But however this npm package works at this [repl bin](https://repl.it/@awsofd/HappyLightsalmonDefinitions#index.js)

I understand that repl.it uses the commonJs version of the NPM Module & we need to use the es6 version in angular project so I am taking the following steps.

1. `npm install --save get-video-duration`
2.  adding `"node_modules/get-video-duration/dist/es6/index.js" `to scripts in angular.json
3.` declare var getVideoDurationInSeconds :any; `in my angular component
```
getVideoDurationInSeconds('http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4').then((duration) => {
      console.log(duration)
    })
```
But however this throws a ReferenceError: Cannot access 'execa' before initialization Error !!!!!!

**Comment by Sumolari** [comment]
This package depends on `execa` and on `ffmpeg` and those are dependencies that as far as I know only support NodeJS environment so you can't run them in the browser.

Maybe in the future with the adoption of WebAssembly this requirement changes but for the time being you can't use them in a client-side Angular project.

An alternative could be adding an endpoint to your backend which returns the duration of the video instead of doing this operation in the client side.

**Comment by BabuBahir** [comment]
Okay .. Thanks for the reply... I understood that the .html was the client side & .ts was the nodeJs....but I was wrong. ..the .ts is just the .js complier so its still client side.... I got your point... I would create a separate nodeJs service which will take url as input &  will return duration
