### ISSUE TITLE
Not working with a Electron Asar archive

### ISSUE THREAD

**Issue by SNRSE** [caffco/get-video-duration#26]
hey , i noticed that this libary is not working inside a asar archcive

**Comment by Sumolari** [comment]
Hi @SNRSE, I’m not familiar with Electron or asar archives, could you provide more info about the error?

**Comment by SNRSE** [comment]
see the descripton of the ffprobe installer : 
const ffprobePath = require('@ffprobe-installer/ffprobe').path.replace(
    'app.asar',
    'app.asar.unpacked'
);

**Comment by SNRSE** [comment]
sorry to bother you again, with the help of another dev i was able to get this code that would solve the problem but wont change the path for anything non electron:
`function getImagesPath(relativePath) { if ((app || remote.app).isPackaged===false) { return path.join(__dirname, relativePath); } else { let asarUnpackedPath = __dirname.replace (/\.asar([\\/])/, '.asar.unpacked$1'); return path.join(asarUnpackedPath, relativePath); } }`

**Comment by SNRSE** [comment]
If you want I can write a PR for this fix. The only problem is I am not sure if we can test it somehow since it would need building an Electron Project and then running the Build project to test. While I can do this manually I can't think about a way to automate this test. Would you still merging the PR?

**Comment by Sumolari** [comment]
I think having an automated test for this is important, specially since I'm not an Electron developer and any future changes I merge might introduce an unnoticed regression here.

This test can be something entirely different than the current tests, it might be a shell script building the Electron project or even a small Electron project using the library to read a well-known file and then building and running it. The important part is being able to run it automatically on each push request using Github Actions, like the other tests are run.

If you can open a PR with the fix and the manual steps to build and test it I might be able to automate it in Github Actions.

**Comment by Sumolari** [comment]
`v4.1.0` has a new, optional, parameter that you can provide to override the path to `ffprobe`. When not provided, `get-video-duration` will take the path from `@ffprobe-installer/ffprobe`.
